[package]
name = "tproxy-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
nix = { version = "0.29.0" , features = ["socket", "net", "user"] }
tokio = { version = "1.38.0", features = ["full"] }
